version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-crud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lgv2ub7g9rp"
s3_prefix = "user-crud"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
